{
 "title": "mcmon",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Server online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mcmon_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(mcmon_online) by (server, value)"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mcmon_players_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max players",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mcmon_players_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mcmon_players_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mcmon_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Protocol version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mcmon_protocol_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "mcmon_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Description",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mcmon_description", "legendFormat": "{{description}}" }
   ]
  }
 ]
}